import logging
import azure.functions as func
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_pdf(data):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.setFont("Helvetica", 12)

    c.drawString(100, 750, "PDF Report Generated by Azure Function")
    c.drawString(100, 720, f"Title: {data.get('title', 'N/A')}")
    c.drawString(100, 700, f"Name: {data.get('name', 'N/A')}")
    c.drawString(100, 680, f"Amount: {data.get('amount', 'N/A')}")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('PDF Generator Function processed a request.')

    try:
        req_body = req.get_json()
    except ValueError:
        return func.HttpResponse("Invalid JSON payload", status_code=400)

    pdf_buffer = create_pdf(req_body)

    return func.HttpResponse(pdf_buffer.read(), mimetype="application/pdf", status_code=200)